routes/web.php
        Route::get('/create', 'UserController@create')->name('create')->middleware('permission:user-create');
        Route::get('/profile/', 'UserController@profile')->name('profile');
        Route::get('/password', 'UserController@password')->name('password');
        Route::get('/edit/{id?}', 'UserController@edit')->name('edit')->middleware('permission:user-edit');
        Route::post('/store', 'UserController@store')->name('store')->middleware('permission:user-create');
        Route::post('/update/{id}', 'UserController@update')->name('update')->middleware('permission:user-edit');
        Route::delete('/delete/{id?}', 'UserController@delete')->name('delete')->middleware('permission:user-delete');
        Route::post('/profile/{id}', 'UserController@editProfile')->name('editProfile');
        Route::put('/password', 'UserController@postChangePassword')->name('postChangePassword');

    });
    //QUAN LY PHAN QUYEN
    Route::group(['prefix' => 'role', 'as' => 'role.'], function () {
        Route::get('/', 'RoleController@index')->name('index')->middleware('permission:role-list');
        Route::get('/create', 'RoleController@create')->name('create')->middleware('permission:role-create');
        Route::get('/edit/{id}', 'RoleController@edit')->name('edit')->middleware('permission:role-edit');
        Route::delete('/delete/{id?}', 'RoleController@delete')->name('delete')->middleware('permission:role-list');
        Route::patch('/update/{id}', 'RoleController@update')->name('update');
        Route::post('/store', 'RoleController@store')->name('store');
    });
    //QUAN LY CAU HINH
    Route::group(['prefix' => 'setting', 'as' => 'setting.'], function () {
        Route::get('/', 'SettingController@system')->name('system')->middleware('permission:config-view');
        Route::post('/post-system', 'SettingController@postSystem')->name('postSystem')->middleware('permission:config-view');
        Route::get('/menu-top', 'SettingController@menu')->name('menu')->middleware('permission:config-view');
        Route::get('/menu-bottom', 'SettingController@menuBottom')->name('menuBottom')->middleware('permission:config-view');
        Route::post('/save-menu', 'SettingController@saveMenu')->name('saveMenu')->middleware('permission:config-view');
        Route::post('/add-menu', 'SettingController@addMenu')->name('addMenu')->middleware('permission:config-view');
        Route::get('/delete-menu', 'SettingController@deleteMenu')->name('deleteMenu')->middleware('permission:config-view');
        Route::get('/socials', 'SettingController@socials')->name('socials')->middleware('permission:config-view');
        Route::post('/add-socials', 'SettingController@addSocial')->name('addSocial')->middleware('permission:config-view');
        Route::get('/about-page', 'SettingController@aboutPage')->name('aboutPage');
        Route::post('/save-about', 'SettingController@saveAbout')->name('saveAbout');
        Route::get('/contact-page', 'SettingController@contactPage')->name('contactPage');
        Route::post('/save-contact-page', 'SettingController@saveContactPage')->name('saveContactPage');
        Route::post('/add-chat', 'SettingController@addChat')->name('addChat');
        Route::post('/upload-editor', 'SettingController@uploadEditor')->name('uploadEditor');
    });
    
    //QUAN LY SAN PHAM
    Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
        Route::get('/', 'ProductController@index')->name('index')->middleware('permission:product-list');
        Route::get('/create', 'ProductController@create')->name('create')->middleware('permission:product-create');
        Route::get('/edit/{id}', 'ProductController@edit')->name('edit')->middleware('permission:product-edit');
        Route::delete('/delete/{id?}', 'ProductController@delete')->name('delete')->middleware('permission:product-delete');
        Route::post('/update/{id}', 'ProductController@update')->name('update')->middleware('permission:product-edit');
        Route::post('/store', 'ProductController@store')->name('store')->middleware('permission:product-create');
        Route::post('/check-slug', 'ProductController@checkSlug')->name('checkSlug');
        
    });
    //QUAN LY TIN TUC
    Route::group(['prefix' => 'news', 'as' => 'news.'], function () {
        Route::get('/', 'NewsController@index')->name('index')->middleware('permission:news-list');
        Route::get('/create', 'NewsController@create')->name('create')->middleware('permission:news-create');
        Route::get('/edit/{id}', 'NewsController@edit')->name('edit')->middleware('permission:news-edit');
        Route::delete('/delete/{id?}', 'NewsController@delete')->name('delete')->middleware('permission:news-delete');
        Route::post('/update/{id}', 'NewsController@update')->name('update')->middleware('permission:news-edit');
        Route::post('/store', 'NewsController@store')->name('store')->middleware('permission:news-create');
        Route::post('/check-slug', 'NewsController@checkSlug')->name('checkSlug');
    });
    
        //QUAN LY Feed back
    Route::group(['prefix' => 'feedback', 'as' => 'feedback.'], function () {
        Route::get('/', 'FeedbackController@index')->name('index');
        Route::get('/create', 'FeedbackController@create')->name('create');
        Route::get('/edit/{id}', 'FeedbackController@edit')->name('edit');
        Route::delete('/delete/{id?}', 'FeedbackController@delete')->name('delete');
        Route::post('/update/{id}', 'FeedbackController@update')->name('update');
        Route::post('/store', 'FeedbackController@store')->name('store');
    });
        //QUAN LY mail
    Route::group(['prefix' => 'mail', 'as' => 'mail.'], function () {
        Route::get('/', 'FeedbackController@mail')->name('index');
        Route::get('/export-mail', 'FeedbackController@exportMail')->name('export');
    });
    
    //QUAN LY PAGE
    Route::group(['prefix' => 'page', 'as' => 'page.'], function () {
        Route::get('/', 'PageController@index')->name('index')->middleware('permission:page-list');
        Route::get('/create', 'PageController@create')->name('create')->middleware('permission:page-create');
        Route::get('/edit/{id}', 'PageController@edit')->name('edit')->middleware('permission:page-edit');
        Route::delete('/delete/{id?}', 'PageController@delete')->name('delete')->middleware('permission:page-delete');
        Route::patch('/update/{id}', 'PageController@update')->name('update')->middleware('permission:page-edit');
        Route::post('/store', 'PageController@store')->name('store')->middleware('permission:page-create');
    });
    //QUAN LY BAN HANG
    Route::group(['prefix' => 'cart', 'as' => 'cart.'], function () {
        Route::get('/', 'CartController@index')->name('index')->middleware('permission:cart-list');
        Route::delete('/delete/{id?}', 'CartController@delete')->name('delete')->middleware('permission:cart-delete');
    });
});
Route::post('/product/upload-file', 'ProductController@uploadFile')->name('admin.uploadFile');
Route::get('/product/crop-file-image', 'ProductController@cropFileImage')->name('admin.cropFileImage');

Route::group(['prefix' => '/', 'namespace' => 'Frontend'], function () {
    Route::get('/', 'DefaultController@landingPage')->name('frontend.landingPage');
    Route::get('/home', 'DefaultController@index')->name('frontend.home');
    Route::get('/contact-us', 'DefaultController@contactUs')->name('frontend.default.contactUs');
    Route::post('/subcribe-email', 'DefaultController@subcribeEmail')->name('frontend.default.subcribeEmail');
    Route::get('/about', 'DefaultController@about')->name('frontend.default.about');
    Route::post('/about/add-contact', 'DefaultController@addContact')->name('frontend.default.addContact');
    Route::get('/search', 'ProductController@search')->name('frontend.search');
    Route::get('/services', 'ProductController@index')->name('frontend.service.index');
    Route::get('/service/purchase', 'ProductController@purchase')->name('frontend.service.purchase');
    Route::get('/service/{slug}', 'ProductController@detail')->name('frontend.service.detail');
    Route::get('/news', 'NewsController@index')->name('frontend.news.index');
    Route::get('/news/{slug}', 'NewsController@detail')->name('frontend.news.detail');
    Route::get('/careers', 'NewsController@career')->name('frontend.news.career');
    Route::get('/careers/{slug}', 'NewsController@detailCareer')->name('frontend.news.detailCareer');
    Route::get('/category/{slug}', 'ProductController@category')->name('frontend.category');
    Route::post('/save-email', 'DefaultController@saveEmail')->name('frontend.saveEmail');
    Route::get('/download-file', 'ProductController@download')->name('frontend.download');
    Route::get('/contributor/{slug}', 'ProductController@contributor')->name('frontend.contributor');
    Route::get('/carts', 'ProductController@carts')->name('frontend.carts');
    Route::get('/list-carts', 'ProductController@carts')->name('frontend.listcarts');
    Route::get('/delete-cart', 'ProductController@deleteCart')->name('frontend.deleteCart');
    Route::post('/add-cart', 'ProductController@addCart')->name('frontend.addCart');
    // User
    Route::get('/user/profile', 'UserController@profile')->name('frontend.user.profile');
    Route::post('/user/check-login', 'DefaultController@checkLogin')->name('frontend.user.checkLogin');
    Route::get('/user/register', 'UserController@register')->name('frontend.user.register');
    Route::post('/user/saveRegister', 'UserController@saveRegister')->name('frontend.user.saveRegister');
    Route::get('/user/done', 'UserController@done')->name('frontend.user.done');
    Route::get('/user/report', 'UserController@report')->name('frontend.user.report');
    Route::get('/user/order-history', 'UserController@orderHistory')->name('frontend.user.orderHistory');

app/Http/Controllers/Frontend/ProductController.php
<?php

/**
 * @package     DMS
 * @category    Product Controller
 * @copyright   Copyright 2018 FPT
 * @author      SonPD1 FSU2.C88
 * @since       2018-08-10
 */

namespace App\Http\Controllers\Frontend;

use App\Helpers\Facades\Tool;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\Product;
use App\Helpers\Pagination;
use Artisan;
use Auth;
use Carbon\Carbon;
use DB;
use Illuminate\Http\Request;
use Session;

class ProductController extends Controller {
    
    /**
     * @description: Màn hình services
     * @author     : SonPD1
     */
    public function index(Request $request) {
        try {
            $data = [];
            $order = $request->get('sort', 1);
            $limit = $request->get('limit', Tool::getConst('DEFAULT_LIMIT'));
            $query = Product::where('status', 1);
            switch ($order) {
                case 1:
                    $query->orderBy('title', 'asc');
                    break;
                case 2:
                    $query->orderBy('title', 'desc');
                    break;
                case 3:
                    $query->orderBy('price', 'desc');
                    break;
                case 4:
                    $query->orderBy('price', 'asc');
                    break;
                case 5:
                    $query->orderBy('id', 'desc');
                    break;
                case 6:
                    $query->orderBy('id', 'asc');
                    break;
                default :
                    break;
            }
            $services = $query->paginate($limit);
            $data['services'] = $services;
            $data['sort'] = $order;
            $data['limit'] = $limit;
            $pagination = Pagination::init($services)->limit(Tool::getConst('PAGGING_LIMIT'))->appends(['sort' => $data['sort'], 'limit' => $limit])->render();
            $data['pagination'] = $pagination;
            return view('frontend.service.index', $data);
        } catch (Exception $e) {
            abort(500);
        }
    }
    
    public function carts(Request $request) {
        try {
            $data = [];
            $data['user'] = Auth::check() ? Auth::user() : null;
            $carts = Session::get('carts');
            $data['carts'] = $carts ? json_decode($carts, true) : null;
            return view('frontend.cart.index', $data);
        } catch (Exception $e) {
            abort(500);
        }
    }
    
    public function addCart(Request $request) {
        $productId = $request->get('productId', null);
        $product = Product::find($productId);
        if ($product) {
            $carts = Session::get('carts');
            $dataCart = [];
            if ($carts) {
                $dataCart = json_decode($carts, true);
            }
            $update = false;
            foreach ($dataCart as $key => $value) {
                if ($value['id'] == $product->id) {
                    $value['total'] = $value['total'] + 1;
                    $dataCart[$key] = $value;
                    $update = true;
                }
            }
            if (!$update) {
                $dataCart[] = [
                    'title' => $product->title,
                    'price' => $product->price,
                    'id' => $product->id,
                    'total' => 1,
                ];
            }
            Session::put('carts', json_encode($dataCart));
            return redirect()->route('frontend.carts')->with([
                'level' => 'success',
                'message' => trans('message.them_dich_vu_thanh_cong')
            ]);
        } else {
            abort(500);
        }
    }
    
    public function deleteCart(Request $request) {
        $indexCart = $request->get('id', null);
        if (!is_null($indexCart)) {
            $carts = Session::get('carts');
            if ($carts) {
                $carts = json_decode($carts, true);
                if (isset($carts[$indexCart])) {
                    unset($carts[$indexCart]);
                }
                $dataCart = array_values($carts);
                Session::put('carts', json_encode($dataCart));
            }
        }
        return redirect()->route('frontend.carts')->with([
            'level' => 'success',
            'message' => trans('message.xoa_thanh_cong')
        ]);
    }
    /**
     * @description: Màn hình detail service
     * @author     : SonPD1
     */
    public function detail(Request $request, $slug) {
        try {
            $user = Auth::user();
            if ($slug) {
                $product = Product::where('slug', $slug)->where('status', 1)->first();
                if ($product) {
                    $urlNow = $request->url();
                    $others = Product::where('status', 1)->where('id', '<>', $product->id)->orderBy('id', 'desc')->take(4)->get();
                    return view('frontend.service.detail', ['product' => $product, 'others' => $others, 'user' => $user, 'urlNow' => $urlNow]);
                }
            }
            abort(404);
        } catch (Exception $e) {
            abort(500);
        }
    }
    
    /**
     * @description: luu thông tin mua hàng
     * @author     : SonPD1
     */
    public function purchase(Request $request) {
        $status = true;
        try {
            $user = Auth::user();
            $productId = $request->get('id', null);
            $product = Product::find($productId);
            if ($product) {
                $carts = Session::get('carts');
                $dataCart = [];
                if ($carts) {
                    $dataCart = json_decode($carts, true);
                    $cartId = DB::table('carts')->insertGetId([
                        'user_id' => $user->id,
                        'created_time' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'status' => 1,
                    ]);
                    if ($cartId) {
                        foreach ($dataCart as $itemCart) {
                            DB::table('cart_product')->insert([
                                'cart_id' => $cartId,
                                'product_id' => $itemCart['id'],
                                'quantity' => $itemCart['total'],
                            ]);
                        }
                        Session::put('carts', null);
                    } else {
                        $status = false;
                    }
                }
            } else {
                $status = false;
            }
        } catch (Exception $e) {
            $status = false;
        }
        return redirect()->route('frontend.home')->with([
            'level' => 'success',
            'message' => trans('message.don_hang_cua_ban_da_gui_thanh_cong')
        ]);
    }
}

resources/views/product/create.blade.php
@extends('layouts.master')
@section('title',trans('message.tao_moi_san_pham'))
@section('head_stylesheet')
    <style>
        .table-wrapper-scroll-y {
            display: block;
            max-height: 500px;
            overflow-y: auto;
            -ms-overflow-style: -ms-autohiding-scrollbar;
        }
    </style>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/jquery.Jcrop.min.css') }}"/>
@endsection
@section('content')
<?php use App\Helpers\Facades\Tool;?>
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-12">
            <h2></h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ route('product.index') }}">{{trans('message.danh_sach_san_pham')}}</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>{{trans('message.tao_moi_san_pham')}}</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h3><i class="fa fa-unlock-alt"></i> {{trans('message.tao_moi_san_pham')}}</h3>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-sm-12">
                                <form id="form-product" name="customFile6" action="{{route('product.store')}}" method="POST" enctype="multipart/form-data">
                                {{ csrf_field() }}
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">{{trans('message.tieu_de')}} <span class="require"></span></label>
                                    <div class="col-sm-10">
                                        <input id="title" type="text" name="title" class="form-control" required value=""
                                               placeholder="{{trans('message.nhap_tieu_de')}} ...">
                                        <span class="help-block"></span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">{{trans('message.slug')}} <span class="require"></span></label>
                                    <div class="col-sm-10">
                                        <input id="slug" type="text" name="slug" class="form-control" required value="" placeholder="{{trans('message.nhap_slug')}} ...">
                                        <span class="help-block"></span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">{{trans('message.gia_ban')}}</label>
                                    <div class="col-sm-10">
                                        <input type="number" min='0' name="price" class="form-control" value=""
                                               placeholder="{{trans('message.nhap_gia_ban')}} ...">
                                        <span class="help-block"></span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">{{ trans('message.mo_ta') }} </label>
                                    <div class="col-sm-10">
                                        <textarea rows="4" name="description" class="form-control"
                                                  placeholder="{{ trans('message.nhap_mo_ta') }}"></textarea>
                                        <span class="help-block"></span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">{{trans('message.noi_dung_chinh')}} </label>
                                    <div class="col-sm-10">
                                        <textarea id="messageArea" rows="7" class="form-control ckeditor" name="content"></textarea>
                                        <span class="help-block"></span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">{{trans('message.ngon_ngu')}} </label>
                                    <div class="col-sm-10">
                                        <select class="form-control" name="lang" style="max-width: 200px">
                                            <option value="vi">{{trans('message.tieng_viet')}}</option>
                                            <option value="en">{{trans('message.tieng_anh')}}</option>
                                        </select>
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <input id="image-file" type="hidden" name="avatar" />
                                    <label class="col-sm-2 col-form-label">{{ trans('message.anh_dai_dien') }}</label>
                                    <div class="col-sm-6 box-upload-file">
                                        <div class="custom-file" style="margin-bottom: 20px;">
                                            <input type-file="image" data-name="customFile6" type="file" name="file_upload" class="custom-file-input" id="customFile6">
                                            <label class="custom-file-label" for="customFile6">{{trans('message.chon_file')}}</label>
                                            <div class="invalid-feedback" style="font-size: 14px;"></div>
                                        </div>
                                        <ul class="list-show-image" style="width: 100%;padding-top:0"></ul>
                                    </div>
                                    <br/>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">{{trans('message.thu_tu')}}</label>
                                    <div class="col-sm-10">
                                        <input id="sort" type="number" name="sort" class="form-control" required value="1">
                                        <span class="help-block"></span>
                                    </div>
                                </div>

                                <div class="hr-line-dashed"></div>
                                <div class="form-group row">
                                    <div class="col-sm-8 offset-2">
                                        <button class="btn btn-primary btn-lg" type="submit"><i
                                                    class="fa fa-save fa-fw"></i> {{ trans('message.luu_lai') }}</button>
                                        <a href="{{ route('product.create') }}">
                                            <button class="btn btn-danger btn-lg" type="button"><i
                                                        class="fa fa-undo fa-fw"></i> {{ trans('message.nhap_lai') }}</button>
                                        </a>
                                    </div>
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="viewDetail" role="dialog">
        <div class="modal-dialog">
        <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">x</button>
                    <h4 class="modal-title" id="detail-pallet-qrcode">{{trans('message.cat_anh')}}</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-12 show-image">
                            <img src="{{ asset('upload') }}/no-image.gif" id="cropbox" class="img" />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" id="crop-image" class="btn btn-info">{{trans('message.cat_anh')}}</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">{{trans('message.dong_lai')}}</button>
                </div>

            </div>
        </div>
    </div>
    <input type="hidden" id="_token" name="_token" value="{{ csrf_token() }}">
@stop
@section('body_script')
    <script type="text/javascript" src="{{asset('js/plugins/ckeditor/ckeditor.js?v='.Tool::getConst('VERSION_JS'))}}"></script>
    <script type="text/javascript" src="{{ asset('js/jquery.Jcrop.min.js?v='.Tool::getConst('VERSION_JS')) }}"></script>
    
   <script>
    CKEDITOR.replace( 'messageArea', {
     height: 500,
     filebrowserImageUploadUrl: "{{route('setting.uploadEditor', ['_token' => csrf_token()])}}"
    });
</script>
    <script>
        var statusImage = false;
        $('.input-group.date').datepicker({
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            calendarWeeks: true,
            autoclose: true,
            format: "d-m-yyyy",
        });

        $("input.img-choice").change(function () {
            var self = $(this);
            self.parent().parent().removeClass('has-error');
            self.parent().parent().parent().find('.help-block').hide();
            var size = parseInt(this.files[0].size);
            if (size > (2097152*5)) {    // 15728640 byte ~ 15MB
                var largestImgCapacity = "{{trans('message.dung_luong_anh_khong_duoc_vuot_qua_10mb')}}";
                self.parent().parent().addClass('has-error');
                self.parent().parent().parent().find('.help-block').text(largestImgCapacity).show();
                statusImage = false;
                return false;
            }
            var extension = $(this).val().split('.').pop().toLowerCase();
            if (extension == 'jpg' || extension == 'png' || extension == 'jpeg') {
                readURL(this);
            } else {
                var formatImg = "{{ trans('message.anh_phai_thuoc_mot_trong_cac_dinh_dang_png_jpg_jpeg') }}";
                statusImage = false;
                self.parent().parent().addClass('has-error');
                self.parent().parent().parent().find('.help-block').text(formatImg).show();
            }
            return false;
        });

        function readURL(input) {
            if (input.files && input.files[0]) {
                var self = $(input);
                var reader = new FileReader();
                reader.onload = e => {
                    self.closest('div.form-group').next('div.form-group').find('img.img-preview').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
                statusImage = true;
            } else {
                statusImage = false;
            }
        }
    </script>
    <script>
        var urlCheckSlug = '{{route('product.checkSlug')}}';
        var uploadFileAttact = '{{route('admin.uploadFile')}}';
        var urlCropFileImage = '{{route('admin.cropFileImage')}}';
        var idTarget = '';
        var RATIO_IMAGE_CARD = <?php echo Tool::getConst('RATIO_IMAGE_CARD');?>;
        var RATIO_POSITION_CARD = <?php echo Tool::getConst('RATIO_POSITION_CARD');?>;
    </script>
    <script>
    $.fn.modal.Constructor.prototype.enforceFocus = function() {
	        var $modalElement = this.$element;
	        $(document).on('focusin.modal',function(e) {
	                var $parent = $(e.target.parentNode);
	                if ($modalElement[0] !== e.target
	                                && !$modalElement.has(e.target).length
	                                && $(e.target).parentsUntil('*[role="dialog"]').length === 0) {
	                        $modalElement.focus();
	                }
	        });
	};
</script>
    <script type="text/javascript" src="{{asset('js/dms/product.js?v='.\App\Helpers\Facades\Tool::getConst('VERSION_JS'))}}"></script>
@endsection