routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();
Route::get('/login', 'AuthController@index')->name('login')->middleware('login');
Route::get('/logout', 'AuthController@logout')->name('logout');
Route::post('/login', 'AuthController@postLogin')->name('postLogin');
Route::get('/lang/{option?}', 'HomeController@setLocale')->name('locale');

Route::group(['middleware' => array('auth', 'locale', 'request', 'admin'), 'prefix' => 'admin'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/addRole', 'HomeController@addRole')->name('addRole');

    //QUAN LY NGUOI DUNG
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('/', 'UserController@index')->name('index')->middleware('permission:user-list');
        Route::get('/create', 'UserController@create')->name('create')->middleware('permission:user-create');
        Route::get('/profile/', 'UserController@profile')->name('profile');
        Route::get('/password', 'UserController@password')->name('password');
        Route::get('/edit/{id?}', 'UserController@edit')->name('edit')->middleware('permission:user-edit');
        Route::post('/store', 'UserController@store')->name('store')->middleware('permission:user-create');
        Route::post('/update/{id}', 'UserController@update')->name('update')->middleware('permission:user-edit');
        Route::delete('/delete/{id?}', 'UserController@delete')->name('delete')->middleware('permission:user-delete');
        Route::post('/profile/{id}', 'UserController@editProfile')->name('editProfile');
        Route::put('/password', 'UserController@postChangePassword')->name('postChangePassword');

    });
    //QUAN LY PHAN QUYEN
    Route::group(['prefix' => 'role', 'as' => 'role.'], function () {
        Route::get('/', 'RoleController@index')->name('index')->middleware('permission:role-list');
        Route::get('/create', 'RoleController@create')->name('create')->middleware('permission:role-create');
        Route::get('/edit/{id}', 'RoleController@edit')->name('edit')->middleware('permission:role-edit');
        Route::delete('/delete/{id?}', 'RoleController@delete')->name('delete')->middleware('permission:role-list');
        Route::patch('/update/{id}', 'RoleController@update')->name('update');
        Route::post('/store', 'RoleController@store')->name('store');
    });
    //QUAN LY CAU HINH
    Route::group(['prefix' => 'setting', 'as' => 'setting.'], function () {
        Route::get('/', 'SettingController@system')->name('system')->middleware('permission:config-view');
        Route::post('/post-system', 'SettingController@postSystem')->name('postSystem')->middleware('permission:config-view');
        Route::get('/menu-top', 'SettingController@menu')->name('menu')->middleware('permission:config-view');
        Route::get('/menu-bottom', 'SettingController@menuBottom')->name('menuBottom')->middleware('permission:config-view');
        Route::post('/save-menu', 'SettingController@saveMenu')->name('saveMenu')->middleware('permission:config-view');
        Route::post('/add-menu', 'SettingController@addMenu')->name('addMenu')->middleware('permission:config-view');
        Route::get('/delete-menu', 'SettingController@deleteMenu')->name('deleteMenu')->middleware('permission:config-view');
        Route::get('/socials', 'SettingController@socials')->name('socials')->middleware('permission:config-view');
        Route::post('/add-socials', 'SettingController@addSocial')->name('addSocial')->middleware('permission:config-view');
        Route::get('/about-page', 'SettingController@aboutPage')->name('aboutPage');
        Route::post('/save-about', 'SettingController@saveAbout')->name('saveAbout');
        Route::get('/contact-page', 'SettingController@contactPage')->name('contactPage');
        Route::post('/save-contact-page', 'SettingController@saveContactPage')->name('saveContactPage');
        Route::post('/add-chat', 'SettingController@addChat')->name('addChat');
        Route::post('/upload-editor', 'SettingController@uploadEditor')->name('uploadEditor');
    });
    
    //QUAN LY SAN PHAM
    Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
        Route::get('/', 'ProductController@index')->name('index')->middleware('permission:product-list');
        Route::get('/create', 'ProductController@create')->name('create')->middleware('permission:product-create');
        Route::get('/edit/{id}', 'ProductController@edit')->name('edit')->middleware('permission:product-edit');
        Route::delete('/delete/{id?}', 'ProductController@delete')->name('delete')->middleware('permission:product-delete');
        Route::post('/update/{id}', 'ProductController@update')->name('update')->middleware('permission:product-edit');
        Route::post('/store', 'ProductController@store')->name('store')->middleware('permission:product-create');
        Route::post('/check-slug', 'ProductController@checkSlug')->name('checkSlug');
        
    });
    //QUAN LY TIN TUC
    Route::group(['prefix' => 'news', 'as' => 'news.'], function () {
        Route::get('/', 'NewsController@index')->name('index')->middleware('permission:news-list');
        Route::get('/create', 'NewsController@create')->name('create')->middleware('permission:news-create');
        Route::get('/edit/{id}', 'NewsController@edit')->name('edit')->middleware('permission:news-edit');
        Route::delete('/delete/{id?}', 'NewsController@delete')->name('delete')->middleware('permission:news-delete');
        Route::post('/update/{id}', 'NewsController@update')->name('update')->middleware('permission:news-edit');
        Route::post('/store', 'NewsController@store')->name('store')->middleware('permission:news-create');
        Route::post('/check-slug', 'NewsController@checkSlug')->name('checkSlug');
    });
    
        //QUAN LY Feed back
    Route::group(['prefix' => 'feedback', 'as' => 'feedback.'], function () {
        Route::get('/', 'FeedbackController@index')->name('index');
        Route::get('/create', 'FeedbackController@create')->name('create');
        Route::get('/edit/{id}', 'FeedbackController@edit')->name('edit');
        Route::delete('/delete/{id?}', 'FeedbackController@delete')->name('delete');
        Route::post('/update/{id}', 'FeedbackController@update')->name('update');
        Route::post('/store', 'FeedbackController@store')->name('store');
    });
        //QUAN LY mail
    Route::group(['prefix' => 'mail', 'as' => 'mail.'], function () {
        Route::get('/', 'FeedbackController@mail')->name('index');
        Route::get('/export-mail', 'FeedbackController@exportMail')->name('export');
    });
    
    //QUAN LY PAGE
    Route::group(['prefix' => 'page', 'as' => 'page.'], function () {
        Route::get('/', 'PageController@index')->name('index')->middleware('permission:page-list');
        Route::get('/create', 'PageController@create')->name('create')->middleware('permission:page-create');
        Route::get('/edit/{id}', 'PageController@edit')->name('edit')->middleware('permission:page-edit');
        Route::delete('/delete/{id?}', 'PageController@delete')->name('delete')->middleware('permission:page-delete');
        Route::patch('/update/{id}', 'PageController@update')->name('update')->middleware('permission:page-edit');
        Route::post('/store', 'PageController@store')->name('store')->middleware('permission:page-create');
    });
    //QUAN LY BAN HANG
    Route::group(['prefix' => 'cart', 'as' => 'cart.'], function () {
        Route::get('/', 'CartController@index')->name('index')->middleware('permission:cart-list');
        Route::delete('/delete/{id?}', 'CartController@delete')->name('delete')->middleware('permission:cart-delete');
    });
});
Route::post('/product/upload-file', 'ProductController@uploadFile')->name('admin.uploadFile');
Route::get('/product/crop-file-image', 'ProductController@cropFileImage')->name('admin.cropFileImage');

Route::group(['prefix' => '/', 'namespace' => 'Frontend'], function () {
    Route::get('/', 'DefaultController@landingPage')->name('frontend.landingPage');
    Route::get('/home', 'DefaultController@index')->name('frontend.home');
    Route::get('/contact-us', 'DefaultController@contactUs')->name('frontend.default.contactUs');
    Route::post('/subcribe-email', 'DefaultController@subcribeEmail')->name('frontend.default.subcribeEmail');
    Route::get('/about', 'DefaultController@about')->name('frontend.default.about');
    Route::post('/about/add-contact', 'DefaultController@addContact')->name('frontend.default.addContact');
    Route::get('/search', 'ProductController@search')->name('frontend.search');
    Route::get('/services', 'ProductController@index')->name('frontend.service.index');
    Route::get('/service/purchase', 'ProductController@purchase')->name('frontend.service.purchase');
    Route::get('/service/{slug}', 'ProductController@detail')->name('frontend.service.detail');
    Route::get('/news', 'NewsController@index')->name('frontend.news.index');
    Route::get('/news/{slug}', 'NewsController@detail')->name('frontend.news.detail');
    Route::get('/careers', 'NewsController@career')->name('frontend.news.career');
    Route::get('/careers/{slug}', 'NewsController@detailCareer')->name('frontend.news.detailCareer');
    Route::get('/category/{slug}', 'ProductController@category')->name('frontend.category');
    Route::post('/save-email', 'DefaultController@saveEmail')->name('frontend.saveEmail');
    Route::get('/download-file', 'ProductController@download')->name('frontend.download');

resources/views/user/index.blade.php
@extends('layouts.master')
@section('title', trans('message.danh_sach_tai_khoan'))
@section('content')
<?php use App\Helpers\Facades\Tool; ?>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <h2></h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('home') }}"><i class="fa fa-home fa-fw"></i> {{ trans('message.trang_chu') }}</a>
            </li>
            <li class="breadcrumb-item active">
                <a href="{{route('user.index')}}"><strong>{{ trans('message.danh_sach_tai_khoan') }}</strong></a>
            </li>
        </ol>
    </div>
</div>
<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h3><i class="fa fa-users fa-fw"></i> {{ trans('message.danh_sach_tai_khoan') }}</h3>
                    @if (Entrust::can('user-create'))
                    <a href="{{ route('user.create') }}" class="btn btn-primary pull-right"><i
                            class="fa fa-plus-square fa-fw"></i> {{ trans('message.them_moi') }}</a>
                    @endif
                </div>
                <div class="ibox-content">
                    <form name="form1" action="{{ route('user.index') }}" method="GET">
                        <div class="row">
                            <div class="col-lg-3 col-sm-6">
                                @include('partials.limit')
                            </div>
                            <div class="col-lg-3 col-md-6">
                                <select id="role_id" class="form-control select2" name="role_id"
                                        onchange="$(this).closest('form').submit();">
                                    <option value="0"> {{ trans('message.chon_nhom_quyen_han') }}</option>
                                    @foreach($roles as $value)
                                    <option @if( isset($_GET['role_id']) && $_GET['role_id'] ==  $value->id ) selected
                                             @endif value="{{$value->id}}">{{$value->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-lg-3 col-sm-6">
                                <div class="input-group" {{ Tool::classError('name_search', $errors) }}>
                                     <input
                                        placeholder="{{ trans('message.nhap_ten_dang_nhap') }}"
                                        type="text" name="q" class="form-control"
                                        value="{{ urldecode(Request::get('q')) ?: null }}">
                                    <span class="input-group-append"> <button type="submit"
                                                                              class="btn btn-sm btn-primary"><i
                                                class="fa fa-search"></i>

                                            @if ($errors->has('name_search'))
                                            <span class="help-block">{{ $errors->first('name_search') }}</span>
                                            @endif

                                        </button> </span>
                                </div>
                            </div>
                        </div>
                    </form>
                    <br>
                    @if(isset($users) && $users->count() > 0)
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th class="text-center">{{ trans('message.hinh_anh') }}</th>
                                    <th class="text-center">{{ trans('message.ten_dang_nhap') }}</th>
                                    <th class="text-center">{{ trans('message.ten') }}</th>
                                    <th class="text-center">{{ trans('message.hom_thu') }}</th>
                                    <th class="text-center">{{ trans('message.dien_thoai') }}</th>
                                    <th class="text-center">{{ trans('message.quyen') }}</th>
                                    <th width="5%" class="text-center">{{ trans('message.thao_tac') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($users as $user)
                                <tr>
                                    <td class="feed-element text-center">
                                        <img alt="image" class="img-circle" width="48px" height="48px"
                                             src="{{ Tool::getImage($user->avatar, \App\Helpers\Facades\Tool::getConst('USER_UPLOAD')) }}">
                                    </td>
                                    <td class="text-center">{{$user->username}}</td>
                                    <td class="text-center">{{$user->full_name}}</td>
                                    <td class="text-center">{{$user->email}}</td>
                                    <td class="text-center">{{$user->phone}}</td>
                                    <td class="text-center">
                                        @if(!empty($user->role()->where('status', \App\Helpers\Facades\Tool::getConst('ACTIVE_ON'))->first()))
                                        {{ $user->role()->first()->name }}
                                        @endif
                                    </td>

                                    <td class="text-center no-wrap">

                                        <form method="post" action="{{ route('user.delete', $user->id ) }}"
                                              accept-charset="UTF-8">

                                            <input name="_method" type="hidden" value="delete">
                                            <input name="user_id" type="hidden" value="{{$user->id}}">
                                            <a title="Chi tiết" href="{{route('frontend.user.profile', ['username' => $user->username])}}" target="_blank" class="btn btn-white btn-sm"><i class="fa fa-eye"></i></a>
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_token" id="token"
                                                   value="{{ csrf_token() }}">
                                            @if (Entrust::can('user-edit'))
                                            <a title="{{ trans('message.sua') }}"
                                               href="{{ route('user.edit',['id'=>$user->id]) }}"
                                               class="btn btn-success btn-sm"><i class="fa fa-edit"></i></a>
                                            @endif
                                            @if (Entrust::can('user-reset'))
                                            <a title="Reset password"
                                               href="{{route('user.resetPassword',['id'=>$user->id])}}"
                                               class="btn btn-warning btn-sm resetPassword"><i class="fa fa-undo"></i></a>
                                            @endif
                                            @if (Entrust::can('user-delete'))
                                            @if(!$user->hasRole('root') || !$user->username == 'administrator')
                                            <button type="button" title="{{ trans('message.xoa') }}"
                                                    class="btn btn-danger btn-sm delete-button"><i
                                                    class="fa fa-trash-o"></i></button>
                                            @endif
                                            @endif
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        @includeif('partials.pagination', [
                        'pagination'  => $pagination,
                        'data'   => $users->toArray(),
                        ])
                    </div>
                    @else
                    @includeIf('partials.empty');
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@stop
@section('body_script')
@includeif('partials.message')
<script>
            $(".resetPassword").click(function () {
    var self = $(this);
            swal({
            buttons: {
            confirm: {
            text: 'OK',
                    value: true,
                    visible: true,
                    className: "",
                    closeModal: true,
            },
                    cancel: {
                    text: 'Cancel',
                            value: null,
                            visible: true,
                            className: "",
                            closeModal: true,
                            buttons: true,
                    },
            },
                    dangerMode: true,
                    title: "{{ trans('message.canh_bao') }}",
                    text: "{{ trans('message.ban_co_muon_reset_mat_khau_cua_nguoi_dung_khong') }}",
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: '{{ trans('message.co') }}',
                    cancelButtonText: '{{ trans('message.khong') }}'
            }).then(function (isConfirm) {
    if (isConfirm.value) {
    var url = self.attr("href");
            window.location.href = url;
            return true;
    } else {
    return false;
    }
    }).catch(swal.noop);
            return false;
    });
            $(".delete-button").click(function () {
    var self = $(this);
            swal({
            buttons: {
            confirm: {
            text: 'OK',
                    value: true,
                    visible: true,
                    className: "",
                    closeModal: true,
            },
                    cancel: {
                    text: 'Cancel',
                            value: null,
                            visible: true,
                            className: "",
                            closeModal: true,
                            buttons: true,
                    },
            },
                    dangerMode: true,
                    title: "{{ trans('message.canh_bao') }}",
                    text: "{{ trans('message.ban_co_muon_xoa_tai_khoan_nay_khong') }}",
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: '{{ trans('message.co') }}',
                    cancelButtonText: '{{ trans('message.khong') }}'
            }).then(function (isConfirm) {
    if (isConfirm.value) {
    self.parent().submit();
            return true;
    } else {
    return false;
    }
    }).catch(swal.noop);
            return false;
    });
</script>
@endsection

resources/views/user/password.blade.php
@extends('layouts.master')
@section('title', trans('message.thay_doi_mat_khau'))
@section('content')
<?php use App\Helpers\Facades\Tool;?>
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-12">
            <h2></h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ route('home') }}"><i class="fa fa-home fa-fw"></i> {{ trans('message.trang_chu') }}</a>
                </li>
                <li class="breadcrumb-item active">
                    <a>{{ trans('message.thay_doi_mat_khau') }}</a>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-12">
                {!! Form::open(['method' => 'PUT', 'action' => 'UserController@postChangePassword', 'class' => 'form-horizontal']) !!}
                <div class="ibox ">
                    <div class="ibox-title">
                        <h3><i class="fa fa-key"></i> {{ trans('message.thay_doi_mat_khau') }}</h3>
                    </div>
                    <div class="ibox-content">
                        {{ csrf_field() }}
                        <div class="form-group row {{ Tool::classError('old_password', $errors) }}">
                            <label class="col-sm-2 col-form-label">{{ trans('message.mat_khau_cu') }} <span class="require"></span></label>
                            <div class="col-sm-6">
                                <input type="password" name="old_password" value="{{ old('old_password') }}" class="form-control" placeholder="{{ trans('message.nhap_mat_khau_cu') }}">
                                @if ($errors->has('old_password'))
                                    <span class="help-block">{{ $errors->first('old_password') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row  {{ Tool::classError('new_password', $errors) }}">
                            <label class="col-sm-2 col-form-label">{{ trans('message.mat_khau_moi') }} <span class="require"></span></label>
                            <div class="col-sm-6">
                                <input type="password" name="new_password" placeholder="{{ trans('message.nhap_mat_khau_moi') }}" class="form-control" value="{{ old('new_password') }}"/>
                                @if ($errors->has('new_password'))
                                    <span class="help-block">{{ $errors->first('new_password') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row  {{ Tool::classError('password_confirmation', $errors) }}">
                            <label class="col-sm-2 col-form-label">{{ trans('message.xac_nhan_mat_khau') }} <span class="require"></span></label>
                            <div class="col-sm-6">
                                <input type="password" name="password_confirmation" placeholder="{{ trans('message.xac_nhan_mat_khau_moi') }}" class="form-control" value="{{ old('password_confirmation') }}"/>
                                @if ($errors->has('password_confirmation'))
                                    <span class="help-block">{{ $errors->first('password_confirmation') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group row">
                            <div class="col-sm-8 offset-2">

                                <button class="btn btn-primary btn-lg" type="button" title="{{ trans('mat_khau') }}"
                                        onclick="event.preventDefault(); commonFunc.confirm(this, '{{ trans('message.mat_khau') }}', 2, 'vi', 'false');"
                                        ><i class="fa fa-save fa-fw"></i> {{ trans('message.luu_lai') }}</button>
                                <a href="{{route('user.password')}}"><button class="btn btn-danger btn-lg" type="button"><i class="fa fa-undo fa-fw"></i> {{ trans('message.nhap_lai') }}</button></a>
                            </div>
                        </div>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@stop
@section('body_script')
    @includeif('partials.message')
@endsection