routes/web.php
        Route::get('/password', 'UserController@password')->name('password');
        Route::get('/edit/{id?}', 'UserController@edit')->name('edit')->middleware('permission:user-edit');
        Route::post('/store', 'UserController@store')->name('store')->middleware('permission:user-create');
        Route::post('/update/{id}', 'UserController@update')->name('update')->middleware('permission:user-edit');
        Route::delete('/delete/{id?}', 'UserController@delete')->name('delete')->middleware('permission:user-delete');
        Route::post('/profile/{id}', 'UserController@editProfile')->name('editProfile');
        Route::put('/password', 'UserController@postChangePassword')->name('postChangePassword');

    });
    //QUAN LY PHAN QUYEN
    Route::group(['prefix' => 'role', 'as' => 'role.'], function () {
        Route::get('/', 'RoleController@index')->name('index')->middleware('permission:role-list');
        Route::get('/create', 'RoleController@create')->name('create')->middleware('permission:role-create');
        Route::get('/edit/{id}', 'RoleController@edit')->name('edit')->middleware('permission:role-edit');
        Route::delete('/delete/{id?}', 'RoleController@delete')->name('delete')->middleware('permission:role-list');
        Route::patch('/update/{id}', 'RoleController@update')->name('update');
        Route::post('/store', 'RoleController@store')->name('store');
    });
    //QUAN LY CAU HINH
    Route::group(['prefix' => 'setting', 'as' => 'setting.'], function () {
        Route::get('/', 'SettingController@system')->name('system')->middleware('permission:config-view');
        Route::post('/post-system', 'SettingController@postSystem')->name('postSystem')->middleware('permission:config-view');
        Route::get('/menu-top', 'SettingController@menu')->name('menu')->middleware('permission:config-view');
        Route::get('/menu-bottom', 'SettingController@menuBottom')->name('menuBottom')->middleware('permission:config-view');
        Route::post('/save-menu', 'SettingController@saveMenu')->name('saveMenu')->middleware('permission:config-view');
        Route::post('/add-menu', 'SettingController@addMenu')->name('addMenu')->middleware('permission:config-view');
        Route::get('/delete-menu', 'SettingController@deleteMenu')->name('deleteMenu')->middleware('permission:config-view');
        Route::get('/socials', 'SettingController@socials')->name('socials')->middleware('permission:config-view');
        Route::post('/add-socials', 'SettingController@addSocial')->name('addSocial')->middleware('permission:config-view');
        Route::get('/about-page', 'SettingController@aboutPage')->name('aboutPage');
        Route::post('/save-about', 'SettingController@saveAbout')->name('saveAbout');
        Route::get('/contact-page', 'SettingController@contactPage')->name('contactPage');
        Route::post('/save-contact-page', 'SettingController@saveContactPage')->name('saveContactPage');
        Route::post('/add-chat', 'SettingController@addChat')->name('addChat');
        Route::post('/upload-editor', 'SettingController@uploadEditor')->name('uploadEditor');
    });
    
    //QUAN LY SAN PHAM
    Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
        Route::get('/', 'ProductController@index')->name('index')->middleware('permission:product-list');
        Route::get('/create', 'ProductController@create')->name('create')->middleware('permission:product-create');
        Route::get('/edit/{id}', 'ProductController@edit')->name('edit')->middleware('permission:product-edit');
        Route::delete('/delete/{id?}', 'ProductController@delete')->name('delete')->middleware('permission:product-delete');
        Route::post('/update/{id}', 'ProductController@update')->name('update')->middleware('permission:product-edit');
        Route::post('/store', 'ProductController@store')->name('store')->middleware('permission:product-create');
        Route::post('/check-slug', 'ProductController@checkSlug')->name('checkSlug');
        
    });
    //QUAN LY TIN TUC
    Route::group(['prefix' => 'news', 'as' => 'news.'], function () {
        Route::get('/', 'NewsController@index')->name('index')->middleware('permission:news-list');
        Route::get('/create', 'NewsController@create')->name('create')->middleware('permission:news-create');
        Route::get('/edit/{id}', 'NewsController@edit')->name('edit')->middleware('permission:news-edit');
        Route::delete('/delete/{id?}', 'NewsController@delete')->name('delete')->middleware('permission:news-delete');
        Route::post('/update/{id}', 'NewsController@update')->name('update')->middleware('permission:news-edit');
        Route::post('/store', 'NewsController@store')->name('store')->middleware('permission:news-create');
        Route::post('/check-slug', 'NewsController@checkSlug')->name('checkSlug');
    });
    
        //QUAN LY Feed back
    Route::group(['prefix' => 'feedback', 'as' => 'feedback.'], function () {
        Route::get('/', 'FeedbackController@index')->name('index');
        Route::get('/create', 'FeedbackController@create')->name('create');
        Route::get('/edit/{id}', 'FeedbackController@edit')->name('edit');
        Route::delete('/delete/{id?}', 'FeedbackController@delete')->name('delete');
        Route::post('/update/{id}', 'FeedbackController@update')->name('update');
        Route::post('/store', 'FeedbackController@store')->name('store');
    });
        //QUAN LY mail
    Route::group(['prefix' => 'mail', 'as' => 'mail.'], function () {
        Route::get('/', 'FeedbackController@mail')->name('index');
        Route::get('/export-mail', 'FeedbackController@exportMail')->name('export');
    });
    
    //QUAN LY PAGE
    Route::group(['prefix' => 'page', 'as' => 'page.'], function () {
        Route::get('/', 'PageController@index')->name('index')->middleware('permission:page-list');
        Route::get('/create', 'PageController@create')->name('create')->middleware('permission:page-create');
        Route::get('/edit/{id}', 'PageController@edit')->name('edit')->middleware('permission:page-edit');
        Route::delete('/delete/{id?}', 'PageController@delete')->name('delete')->middleware('permission:page-delete');
        Route::patch('/update/{id}', 'PageController@update')->name('update')->middleware('permission:page-edit');
        Route::post('/store', 'PageController@store')->name('store')->middleware('permission:page-create');
    });
    //QUAN LY BAN HANG
    Route::group(['prefix' => 'cart', 'as' => 'cart.'], function () {
        Route::get('/', 'CartController@index')->name('index')->middleware('permission:cart-list');
        Route::delete('/delete/{id?}', 'CartController@delete')->name('delete')->middleware('permission:cart-delete');
    });
});
Route::post('/product/upload-file', 'ProductController@uploadFile')->name('admin.uploadFile');
Route::get('/product/crop-file-image', 'ProductController@cropFileImage')->name('admin.cropFileImage');

Route::group(['prefix' => '/', 'namespace' => 'Frontend'], function () {
    Route::get('/', 'DefaultController@landingPage')->name('frontend.landingPage');
    Route::get('/home', 'DefaultController@index')->name('frontend.home');
    Route::get('/contact-us', 'DefaultController@contactUs')->name('frontend.default.contactUs');
    Route::post('/subcribe-email', 'DefaultController@subcribeEmail')->name('frontend.default.subcribeEmail');
    Route::get('/about', 'DefaultController@about')->name('frontend.default.about');
    Route::post('/about/add-contact', 'DefaultController@addContact')->name('frontend.default.addContact');
    Route::get('/search', 'ProductController@search')->name('frontend.search');
    Route::get('/services', 'ProductController@index')->name('frontend.service.index');
    Route::get('/service/purchase', 'ProductController@purchase')->name('frontend.service.purchase');
    Route::get('/service/{slug}', 'ProductController@detail')->name('frontend.service.detail');
    Route::get('/news', 'NewsController@index')->name('frontend.news.index');
    Route::get('/news/{slug}', 'NewsController@detail')->name('frontend.news.detail');
    Route::get('/careers', 'NewsController@career')->name('frontend.news.career');
    Route::get('/careers/{slug}', 'NewsController@detailCareer')->name('frontend.news.detailCareer');
    Route::get('/category/{slug}', 'ProductController@category')->name('frontend.category');
    Route::post('/save-email', 'DefaultController@saveEmail')->name('frontend.saveEmail');
    Route::get('/download-file', 'ProductController@download')->name('frontend.download');
    Route::get('/contributor/{slug}', 'ProductController@contributor')->name('frontend.contributor');
    Route::get('/carts', 'ProductController@carts')->name('frontend.carts');
    Route::get('/list-carts', 'ProductController@carts')->name('frontend.listcarts');
    Route::get('/delete-cart', 'ProductController@deleteCart')->name('frontend.deleteCart');
    Route::post('/add-cart', 'ProductController@addCart')->name('frontend.addCart');
    // User
    Route::get('/user/profile', 'UserController@profile')->name('frontend.user.profile');
    Route::post('/user/check-login', 'DefaultController@checkLogin')->name('frontend.user.checkLogin');
    Route::get('/user/register', 'UserController@register')->name('frontend.user.register');
    Route::post('/user/saveRegister', 'UserController@saveRegister')->name('frontend.user.saveRegister');
    Route::get('/user/done', 'UserController@done')->name('frontend.user.done');
    Route::get('/user/report', 'UserController@report')->name('frontend.user.report');
    Route::get('/user/order-history', 'UserController@orderHistory')->name('frontend.user.orderHistory');
    Route::post('/user/saveReport', 'UserController@saveReport')->name('frontend.user.saveReport');
    Route::post('/user/change-pass', 'UserController@changePass')->name('frontend.user.changePass');

app/Http/Controllers/FeedbackController.php
<?php

/**
 * @package     FeedbackController
 * @category    Feedback Controller
 * @copyright   Copyright 2018 FPT
 * @author      SonPD1 FSU2.C88
 * @since       2018-08-10
 */

namespace App\Http\Controllers;

use App\Helpers\Facades\Tool;
use App\Helpers\Pagination;
use App\Models\Feedback;
use App\Models\Contact;
use DB;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Auth;

class FeedbackController extends Controller {
    
    /*
     * @description: Danh sách feedback
     * @input: $request
     * @output: thông tin tin tức
     * @author: SonPD1
     * @created at: 17/8/2018
     * *** */
    public function index(Request $request) {
        $limit = $request->get('limit') ?: Tool::getConst('DEFAULT_LIMIT');
        $q = $request->get('q', null);
        $data['limit'] = $limit;
        $append = compact('q', 'limit');
        $data['feedbacks'] = Feedback::fetchAll($limit, $q, 'id', 'desc');
        $data['pagination'] = Pagination::init($data['feedbacks'])
            ->limit(Tool::getConst('PAGGING_LIMIT'))
            ->appends($append)
            ->render();
        return view('feedback.index', $data, $append);
    }
    
    /*
     * @description: Danh sách mail
     * @input: $request
     * @output: thông tin tin tức
     * @author: SonPD1
     * @created at: 17/8/2018
     * *** */
    public function mail(Request $request) {
        $limit = $request->get('limit') ?: Tool::getConst('DEFAULT_LIMIT');
        $q = $request->get('q', null);
        $data['limit'] = $limit;
        $append = compact('q', 'limit');
        $data['mails'] = Contact::fetchAll($limit, $q, 'id', 'desc');
        $data['pagination'] = Pagination::init($data['mails'])
            ->limit(Tool::getConst('PAGGING_LIMIT'))
            ->appends($append)
            ->render();
        return view('feedback.mail', $data, $append);
    }
    
    /*
     * @description: export mail
     * @input: $request
     * @output: thông tin tin tức
     * @author: SonPD1
     * @created at: 17/8/2018
     * *** */
    public function exportMail(Request $request) {
        $mails = Contact::whereNotNull('email')->pluck('email')->toArray();
        // Export Excel
        $spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setCellValue('A1', 'Danh sách mail');
        $sheet->getStyle('A1')->getFont()->setSize(18)->setBold(true);
        $totalLine = 4;
        foreach ($mails as $mail) {
            $sheet->setCellValue('A' . $totalLine, $mail);
            $totalLine += 1;
        }

        $writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
        ob_end_clean();
        header('Content-Type: application/vnd.ms-excel');
        header('Content-Disposition: Attachment;filename="Danh-sach-mail.xlsx');
        header('Cache-Control: max-age=0');
        $writer->save('php://output');
    }

    /*
     * @description: Create tin tức
     * @input: $request
     * @output: Create tin tức
     * @author: SonPD1
     * @created at: 17/8/2018
     * *** */
    public function create() {
        try {
            $products = \App\Models\Product::where('status', 1)->get();
            $users = \App\Models\User::where('status', 1)->get();
            return view('feedback.create', ['products' => $products, 'users' => $users]);
        } catch (Exception $e) {
            abort(500);
        }
    }
    
    /*
     * @description: Create tin tức
     * @input: $request
     * @output: Create tin tức
     * @author: SonPD1
     * @created at: 17/8/2018
     * *** */
    public function store(Request $request) {
        try {
            Feedback::storeInstance($request);
            return redirect()->route('feedback.index')->with([
                        'message' => trans('message.them_moi_phan_hoi_thanh_cong'),
                        'level' => 'success',
            ]);
        } catch (Exception $e) {
            abort(500);
        }
    }

    /*
     * @description: Edit tin tức
     * @input: $id
     * @output: Edit tin tức
     * @author: SonPD1
     * @created at: 17/8/2018
     * *** */
    public function edit($id) {
        $post = Feedback::findOrFail($id);
        if (!empty($post)) {
            $products = \App\Models\Product::where('status', 1)->get();
            $users = \App\Models\User::where('status', 1)->get();
            return view('feedback.edit', [
                'post' => $post,
                'products' => $products,
                'users' => $users
            ]);
        }
        abort(404);
    }

    /*
     * @description: lưu tin tức
     * @input: $id, $request
     * @output: lưu tin tức
     * @author: SonPD1
     * @created at: 17/8/2018
     * *** */
    public function update(Request $request, $id) {
        $post = Feedback::findOrFail($id);
        Feedback::updateInstance($request, $post);
        return redirect()->route('feedback.index')->with([
                    'message' => trans('message.cap_nhat_phan_hoi_thanh_cong'),
                    'level' => 'success',
        ]);
    }

    /*
     * @description: xóa tin tức
     * @input: id
     * @output: xóa tin tức
     * @author: SonPD1
     * @created at: 17/8/2018
     * *** */

    public function delete(Request $request, $id) {
        try {
            $status = $request->get('status', 0);
            DB::table('feedbacks')->where('id', $id)->update(['status' => $status]);
            $message = $status ? 'Active phản hồi thành công!' : trans('message.xoa_phan_hoi_thanh_cong');
            return back()->with(['level' => 'success', 'message' => $message]);
        } catch (Exception $e) {
            abort(500);
        }
    }

}

resources/views/feedback/create.blade.php
@extends('layouts.master')
@section('title',trans('message.tao_moi_phan_hoi'))
@section('head_stylesheet')
    <style>
        .table-wrapper-scroll-y {
            display: block;
            max-height: 500px;
            overflow-y: auto;
            -ms-overflow-style: -ms-autohiding-scrollbar;
        }
    </style>
@endsection
@section('content')
<?php use App\Helpers\Facades\Tool;?>
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-12">
            <h2></h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ route('feedback.index') }}">{{trans('message.danh_sach_phan_hoi')}}</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>{{trans('message.tao_moi_phan_hoi')}}</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h3><i class="fa fa-unlock-alt"></i> {{trans('message.tao_moi_phan_hoi')}}</h3>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-sm-12">
                                <form id="form-feedback" name="customFile6" action="{{route('feedback.store')}}" method="POST" enctype="multipart/form-data">
                                {{ csrf_field() }}
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">{{trans('message.san_pham')}} <span class="require"></span></label>
                                    <div class="col-sm-10">
                                        <select name="product_id" class='form-control' required>
                                            <option value="">Chọn sản phẩm</option>
                                            <?php if ($products->count() > 0) {
                                            foreach ($products as $product) {?>
                                            <option value="{{$product->id}}">{{$product->title}}</option>
                                            <?php }} ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">{{trans('message.tai_khoan')}} <span class="require"></span></label>
                                    <div class="col-sm-10">
                                        <select name="user_id" class='form-control' required>
                                            <option value="">Chọn tài khoản</option>
                                            <?php if ($users->count() > 0) {
                                            foreach ($users as $user) {?>
                                            <option value="{{$user->id}}">{{$user->full_name}}</option>
                                            <?php }} ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">{{trans('message.noi_dung_chinh')}} </label>
                                    <div class="col-sm-10">
                                        <textarea id="messageArea" rows="7" class="form-control ckeditor" name="content"></textarea>
                                        <span class="help-block"></span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">{{ trans('message.anh_dai_dien') }}</label>
                                    <div class="col-sm-6 box-upload-file">
                                        <div class="custom-file" style="margin-bottom: 20px;">
                                            <input type="file" name="avatar" accept="image/*" />
                                            <div class="invalid-feedback" style="font-size: 14px;"></div>
                                        </div>
                                    </div>
                                    <br/>
                                </div>

                                <div class="hr-line-dashed"></div>
                                <div class="form-group row">
                                    <div class="col-sm-8 offset-2">
                                        <button class="btn btn-primary btn-lg" type="submit"><i
                                                    class="fa fa-save fa-fw"></i> {{ trans('message.luu_lai') }}</button>
                                        <a href="{{ route('feedback.create') }}">
                                            <button class="btn btn-danger btn-lg" type="button"><i
                                                        class="fa fa-undo fa-fw"></i> {{ trans('message.nhap_lai') }}</button>
                                        </a>
                                    </div>
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <input type="hidden" id="_token" name="_token" value="{{ csrf_token() }}">
@stop
@section('body_script')
    <script type="text/javascript" src="{{asset('js/plugins/ckeditor/ckeditor.js?v='.Tool::getConst('VERSION_JS'))}}"></script>
    
   <script>
    CKEDITOR.replace( 'messageArea', {
     height: 500,
     filebrowserImageUploadUrl: "{{route('setting.uploadEditor', ['_token' => csrf_token()])}}"
    });
</script>
    <script>
        var statusImage = false;
        $('.input-group.date').datepicker({
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            calendarWeeks: true,
            autoclose: true,
            format: "d-m-yyyy",
        });
    </script>
    
@endsection

resources/views/feedback/edit.blade.php
@extends('layouts.master')
@section('title',trans('message.cap_nhat_phan_hoi'))
@section('head_stylesheet')
    <style>
        .table-wrapper-scroll-y {
            display: block;
            max-height: 500px;
            overflow-y: auto;
            -ms-overflow-style: -ms-autohiding-scrollbar;
        }
    </style>
@endsection
@section('content')
<?php use App\Helpers\Facades\Tool;?>
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-12">
            <h2></h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ route('feedback.index') }}">{{trans('message.danh_sach_phan_hoi_khach_hang')}}</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>{{trans('message.cap_nhat_phan_hoi')}}</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h3><i class="fa fa-unlock-alt"></i> {{trans('message.cap_nhat_phan_hoi')}}</h3>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-sm-12">
                                <form id="form-feedback" name="customFile6" action="{{route('feedback.update', ['id' => $post->id])}}" method="POST" enctype="multipart/form-data">
                                {{ csrf_field() }}
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">{{trans('message.san_pham')}} <span class="require"></span></label>
                                    <div class="col-sm-10">
                                        <select name="product_id" class='form-control' required>
                                            <option value="">Chọn sản phẩm</option>
                                            <?php if ($products->count() > 0) {
                                            foreach ($products as $product) {?>
                                            <option value="{{$product->id}}" {{($post->product_id == $product->id) ? 'selected' : ''}}>{{$product->title}}</option>
                                            <?php }} ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">{{trans('message.tai_khoan')}} <span class="require"></span></label>
                                    <div class="col-sm-10">
                                        <select name="user_id" class='form-control' required>
                                            <option value="">Chọn tài khoản</option>
                                            <?php if ($users->count() > 0) {
                                            foreach ($users as $user) {?>
                                            <option value="{{$user->id}}" {{($post->user_id == $user->id) ? 'selected' : ''}}>{{$user->full_name}}</option>
                                            <?php }} ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">{{trans('message.noi_dung_chinh')}} </label>
                                    <div class="col-sm-10">
                                        <textarea id="messageArea" rows="7" class="form-control ckeditor" name="content">{!!$post->content!!}</textarea>
                                        <span class="help-block"></span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">{{ trans('message.anh_dai_dien') }}</label>
                                    <div class="col-sm-6 box-upload-file">
                                        <div class="custom-file" style="margin-bottom: 20px;">
                                            <input type="file" name="avatar" accept="image/*" />
                                            <div class="invalid-feedback" style="font-size: 14px;"></div>
                                        </div>
                                        <ul class="list-show-image" style="width: 100%;padding-top:0">
                                            <?php if ($post->avatar) {?>
                                            <li class="col-12">
                                                <img class="new-image-crop" src="{{ Tool::getImage($post->avatar, Tool::getConst('POST_UPLOAD')) }}">
                                            </li>
                                            <?php } ?>
                                        </ul>
                                    </div>
                                    <br/>
                                </div>

                                <div class="hr-line-dashed"></div>
                                <div class="form-group row">
                                    <div class="col-sm-8 offset-2">
                                        <button class="btn btn-primary btn-lg" type="submit"><i
                                                    class="fa fa-save fa-fw"></i> {{ trans('message.luu_lai') }}</button>
                                        <a href="{{ route('feedback.create') }}">
                                            <button class="btn btn-danger btn-lg" type="button"><i
                                                        class="fa fa-undo fa-fw"></i> {{ trans('message.nhap_lai') }}</button>
                                        </a>
                                    </div>
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <input type="hidden" id="_token" name="_token" value="{{ csrf_token() }}">
@stop
@section('body_script')
    <script type="text/javascript" src="{{asset('js/plugins/ckeditor/ckeditor.js?v='.\App\Helpers\Facades\Tool::getConst('VERSION_JS'))}}"></script>
    <script type="text/javascript">
        CKEDITOR.replace( 'messageArea',
            {
             height: 500,
     filebrowserImageUploadUrl: "{{route('setting.uploadEditor', ['_token' => csrf_token()])}}"
             })
   </script> 
@endsection