routes/web.php
        Route::get('/password', 'UserController@password')->name('password');
        Route::get('/edit/{id?}', 'UserController@edit')->name('edit')->middleware('permission:user-edit');
        Route::post('/store', 'UserController@store')->name('store')->middleware('permission:user-create');
        Route::post('/update/{id}', 'UserController@update')->name('update')->middleware('permission:user-edit');
        Route::delete('/delete/{id?}', 'UserController@delete')->name('delete')->middleware('permission:user-delete');
        Route::post('/profile/{id}', 'UserController@editProfile')->name('editProfile');
        Route::put('/password', 'UserController@postChangePassword')->name('postChangePassword');

    });
    //QUAN LY PHAN QUYEN
    Route::group(['prefix' => 'role', 'as' => 'role.'], function () {
        Route::get('/', 'RoleController@index')->name('index')->middleware('permission:role-list');
        Route::get('/create', 'RoleController@create')->name('create')->middleware('permission:role-create');
        Route::get('/edit/{id}', 'RoleController@edit')->name('edit')->middleware('permission:role-edit');
        Route::delete('/delete/{id?}', 'RoleController@delete')->name('delete')->middleware('permission:role-list');
        Route::patch('/update/{id}', 'RoleController@update')->name('update');
        Route::post('/store', 'RoleController@store')->name('store');
    });
    //QUAN LY CAU HINH
    Route::group(['prefix' => 'setting', 'as' => 'setting.'], function () {
        Route::get('/', 'SettingController@system')->name('system')->middleware('permission:config-view');
        Route::post('/post-system', 'SettingController@postSystem')->name('postSystem')->middleware('permission:config-view');
        Route::get('/menu-top', 'SettingController@menu')->name('menu')->middleware('permission:config-view');
        Route::get('/menu-bottom', 'SettingController@menuBottom')->name('menuBottom')->middleware('permission:config-view');
        Route::post('/save-menu', 'SettingController@saveMenu')->name('saveMenu')->middleware('permission:config-view');
        Route::post('/add-menu', 'SettingController@addMenu')->name('addMenu')->middleware('permission:config-view');
        Route::get('/delete-menu', 'SettingController@deleteMenu')->name('deleteMenu')->middleware('permission:config-view');
        Route::get('/socials', 'SettingController@socials')->name('socials')->middleware('permission:config-view');
        Route::post('/add-socials', 'SettingController@addSocial')->name('addSocial')->middleware('permission:config-view');
        Route::get('/about-page', 'SettingController@aboutPage')->name('aboutPage');
        Route::post('/save-about', 'SettingController@saveAbout')->name('saveAbout');
        Route::get('/contact-page', 'SettingController@contactPage')->name('contactPage');
        Route::post('/save-contact-page', 'SettingController@saveContactPage')->name('saveContactPage');
        Route::post('/add-chat', 'SettingController@addChat')->name('addChat');
        Route::post('/upload-editor', 'SettingController@uploadEditor')->name('uploadEditor');
    });
    
    //QUAN LY SAN PHAM
    Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
        Route::get('/', 'ProductController@index')->name('index')->middleware('permission:product-list');
        Route::get('/create', 'ProductController@create')->name('create')->middleware('permission:product-create');
        Route::get('/edit/{id}', 'ProductController@edit')->name('edit')->middleware('permission:product-edit');
        Route::delete('/delete/{id?}', 'ProductController@delete')->name('delete')->middleware('permission:product-delete');
        Route::post('/update/{id}', 'ProductController@update')->name('update')->middleware('permission:product-edit');
        Route::post('/store', 'ProductController@store')->name('store')->middleware('permission:product-create');
        Route::post('/check-slug', 'ProductController@checkSlug')->name('checkSlug');
        
    });
    //QUAN LY TIN TUC
    Route::group(['prefix' => 'news', 'as' => 'news.'], function () {
        Route::get('/', 'NewsController@index')->name('index')->middleware('permission:news-list');
        Route::get('/create', 'NewsController@create')->name('create')->middleware('permission:news-create');
        Route::get('/edit/{id}', 'NewsController@edit')->name('edit')->middleware('permission:news-edit');
        Route::delete('/delete/{id?}', 'NewsController@delete')->name('delete')->middleware('permission:news-delete');
        Route::post('/update/{id}', 'NewsController@update')->name('update')->middleware('permission:news-edit');
        Route::post('/store', 'NewsController@store')->name('store')->middleware('permission:news-create');
        Route::post('/check-slug', 'NewsController@checkSlug')->name('checkSlug');
    });
    
        //QUAN LY Feed back
    Route::group(['prefix' => 'feedback', 'as' => 'feedback.'], function () {
        Route::get('/', 'FeedbackController@index')->name('index');
        Route::get('/create', 'FeedbackController@create')->name('create');
        Route::get('/edit/{id}', 'FeedbackController@edit')->name('edit');
        Route::delete('/delete/{id?}', 'FeedbackController@delete')->name('delete');
        Route::post('/update/{id}', 'FeedbackController@update')->name('update');
        Route::post('/store', 'FeedbackController@store')->name('store');
    });
        //QUAN LY mail
    Route::group(['prefix' => 'mail', 'as' => 'mail.'], function () {
        Route::get('/', 'FeedbackController@mail')->name('index');
        Route::get('/export-mail', 'FeedbackController@exportMail')->name('export');
    });
    
    //QUAN LY PAGE
    Route::group(['prefix' => 'page', 'as' => 'page.'], function () {
        Route::get('/', 'PageController@index')->name('index')->middleware('permission:page-list');
        Route::get('/create', 'PageController@create')->name('create')->middleware('permission:page-create');
        Route::get('/edit/{id}', 'PageController@edit')->name('edit')->middleware('permission:page-edit');
        Route::delete('/delete/{id?}', 'PageController@delete')->name('delete')->middleware('permission:page-delete');
        Route::patch('/update/{id}', 'PageController@update')->name('update')->middleware('permission:page-edit');
        Route::post('/store', 'PageController@store')->name('store')->middleware('permission:page-create');
    });
    //QUAN LY BAN HANG
    Route::group(['prefix' => 'cart', 'as' => 'cart.'], function () {
        Route::get('/', 'CartController@index')->name('index')->middleware('permission:cart-list');
        Route::delete('/delete/{id?}', 'CartController@delete')->name('delete')->middleware('permission:cart-delete');
    });
});
Route::post('/product/upload-file', 'ProductController@uploadFile')->name('admin.uploadFile');
Route::get('/product/crop-file-image', 'ProductController@cropFileImage')->name('admin.cropFileImage');

Route::group(['prefix' => '/', 'namespace' => 'Frontend'], function () {
    Route::get('/', 'DefaultController@landingPage')->name('frontend.landingPage');
    Route::get('/home', 'DefaultController@index')->name('frontend.home');
    Route::get('/contact-us', 'DefaultController@contactUs')->name('frontend.default.contactUs');
    Route::post('/subcribe-email', 'DefaultController@subcribeEmail')->name('frontend.default.subcribeEmail');
    Route::get('/about', 'DefaultController@about')->name('frontend.default.about');
    Route::post('/about/add-contact', 'DefaultController@addContact')->name('frontend.default.addContact');
    Route::get('/search', 'ProductController@search')->name('frontend.search');
    Route::get('/services', 'ProductController@index')->name('frontend.service.index');
    Route::get('/service/purchase', 'ProductController@purchase')->name('frontend.service.purchase');
    Route::get('/service/{slug}', 'ProductController@detail')->name('frontend.service.detail');
    Route::get('/news', 'NewsController@index')->name('frontend.news.index');
    Route::get('/news/{slug}', 'NewsController@detail')->name('frontend.news.detail');
    Route::get('/careers', 'NewsController@career')->name('frontend.news.career');
    Route::get('/careers/{slug}', 'NewsController@detailCareer')->name('frontend.news.detailCareer');
    Route::get('/category/{slug}', 'ProductController@category')->name('frontend.category');
    Route::post('/save-email', 'DefaultController@saveEmail')->name('frontend.saveEmail');
    Route::get('/download-file', 'ProductController@download')->name('frontend.download');
    Route::get('/contributor/{slug}', 'ProductController@contributor')->name('frontend.contributor');
    Route::get('/carts', 'ProductController@carts')->name('frontend.carts');
    Route::get('/list-carts', 'ProductController@carts')->name('frontend.listcarts');
    Route::get('/delete-cart', 'ProductController@deleteCart')->name('frontend.deleteCart');
    Route::post('/add-cart', 'ProductController@addCart')->name('frontend.addCart');
    // User
    Route::get('/user/profile', 'UserController@profile')->name('frontend.user.profile');
    Route::post('/user/check-login', 'DefaultController@checkLogin')->name('frontend.user.checkLogin');
    Route::get('/user/register', 'UserController@register')->name('frontend.user.register');
    Route::post('/user/saveRegister', 'UserController@saveRegister')->name('frontend.user.saveRegister');
    Route::get('/user/done', 'UserController@done')->name('frontend.user.done');
    Route::get('/user/report', 'UserController@report')->name('frontend.user.report');
    Route::get('/user/order-history', 'UserController@orderHistory')->name('frontend.user.orderHistory');
    Route::post('/user/saveReport', 'UserController@saveReport')->name('frontend.user.saveReport');
    Route::post('/user/change-pass', 'UserController@changePass')->name('frontend.user.changePass');

app/Http/Controllers/Frontend/NewsController.php
<?php

/**
 * @package     DMS
 * @category    Product Controller
 * @copyright   Copyright 2018 FPT
 * @author      SonPD1 FSU2.C88
 * @since       2018-08-10
 */

namespace App\Http\Controllers\Frontend;

use App\Helpers\Facades\Tool;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\News;
use App\Helpers\Pagination;
use Artisan;
use Carbon\Carbon;
use DB;
use Illuminate\Http\Request;
use Session;
use Auth;

class NewsController extends Controller {
    
    /**
     * @description: Màn hình tin tuc
     * @author     : SonPD1
     */
    public function index(Request $request) {
        try {
            $data = [];
            $order = $request->get('sort', 1);
            $q = $request->get('q', null);
            $limit = $request->get('limit', Tool::getConst('DEFAULT_LIMIT'));
            $query = News::where('status', 1)->where('type', 1);
            if (strlen(trim($q)) > 0) {
                $query = $query->where(function ($querySub) use ($q) {
                    $querySub->where('posts.title', 'LIKE', '%' . Tool::sanitizeQuery($q) . '%');
                });
            }
            $data['sortName'] = 'Mới nhất';
            switch ($order) {
                case 1:
                    $query->orderBy('id', 'desc');
                    $data['sortName'] = 'Mới nhất';
                    break;
                case 2:
                    $query->orderBy('id', 'asc');
                    $data['sortName'] = 'Cũ nhất';
                    break;
                default :
                    break;
            }
            $posts = $query->paginate($limit);
            $data['posts'] = $posts;
            $data['search'] = $q;
            $data['sort'] = $order;
            $data['limit'] = $limit;
            $pagination = Pagination::init($posts)->limit(Tool::getConst('PAGGING_LIMIT'))->appends(['sort' => $data['sort'], 'limit' => $limit, 'q' => $q])->render();
            $data['pagination'] = $pagination;
            return view('frontend.news.index', $data);
        } catch (Exception $e) {
            abort(500);
        }
    }
    
    /**
     * @description: Màn hình career
     * @author     : SonPD1
     */
    public function career(Request $request) {
        try {
            $data = [];
            $order = $request->get('sort', 1);
            $q = $request->get('q', null);
            $limit = $request->get('limit', Tool::getConst('DEFAULT_LIMIT'));
            $query = News::where('status', 1)->where('type', 2);
            if (strlen(trim($q)) > 0) {
                $select = $select->where(function ($query) use ($q) {
                    $query->where('posts.title', 'LIKE', '%' . Tool::sanitizeQuery($q) . '%');
                });
            }
            $data['sortName'] = 'Mới nhất';
            switch ($order) {
                case 1:
                    $query->orderBy('id', 'desc');
                    $data['sortName'] = 'Mới nhất';
                    break;
                case 2:
                    $query->orderBy('id', 'asc');
                    $data['sortName'] = 'Cũ nhất';
                    break;
                case 3:
                    $query->orderBy('price', 'desc');
                    $data['sortName'] = 'Giá từ cao đến thấp';
                    break;
                case 4:
                    $query->orderBy('price', 'asc');
                    $data['sortName'] = 'Giá từ thấp đến cao';
                    break;
                default :
                    break;
            }
            $posts = $query->paginate($limit);
            $data['posts'] = $posts;
            $data['search'] = $q;
            $data['sort'] = $order;
            $data['limit'] = $limit;
            $pagination = Pagination::init($posts)->limit(Tool::getConst('PAGGING_LIMIT'))->appends(['sort' => $data['sort'], 'limit' => $limit, 'q' => $q])->render();
            $data['pagination'] = $pagination;
            return view('frontend.news.career', $data);
        } catch (Exception $e) {
            abort(500);
        }
    }
    
    /**
     * @description: Màn hình detail
     * @author     : SonPD1
     */
    public function detail(Request $request, $slug) {
        try {
            if ($slug) {
                $post = News::where('slug', $slug)->where('status', 1)->first();
                if ($post) {
                    if ($post->is_require && !Auth::check()) {
                        return redirect()->route('login')->with([
                            'level' => 'error',
                            'error' => trans('message.ban_can_dang_nhap_de_doc_bai_viet_nay')
                        ]);
                    }
                    $others = News::where('status', 1)->where('id', '<>', $post->id)->where('type', 1)->orderBy('id', 'desc')->take(3)->get();
                    return view('frontend.news.detail', ['post' => $post, 'others' => $others]);
                }
            }
            abort(404);
        } catch (Exception $e) {
            abort(500);
        }
    }
    
    /**
     * @description: Màn hình detail career
     * @author     : SonPD1
     */
    public function detailCareer(Request $request, $slug) {
        try {
            if ($slug) {
                $post = News::where('slug', $slug)->where('status', 1)->first();
                if ($post) {
                    $others = News::where('status', 1)->where('id', '<>', $post->id)->where('type', 2)->orderBy('id', 'desc')->take(3)->get();
                    return view('frontend.news.detail-career', ['post' => $post, 'others' => $others]);
                }
            }
            abort(404);
        } catch (Exception $e) {
            abort(500);
        }
    }
}

resources/views/news/index.blade.php
@extends('layouts.master')
@section('title', trans('message.danh_sach_tin_tuc'))
@section('content')
<?php use App\Helpers\Facades\Tool; ?>
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-12">
            <h2></h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item active">
                    <a href="{{route('news.index')}}"><strong>{{trans('message.danh_sach_tin_tuc')}}</strong></a>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h3><i class="fa fa-unlock-alt"></i> {{trans('message.danh_sach_tin_tuc')}}</h3>
                        <a href="{{ route('news.create') }}" class="btn btn-primary pull-right"><i class="fa fa-plus-square fa-fw"></i> {{ trans('message.them_moi') }}</a>
                    </div>
                    <div class="ibox-content">
                        <form name="form1" action="{{route('news.index')}}" method="GET">
                            <div class="row">
                                <div class="col-lg-3 col-sm-6">
                                    @include('partials.limit')
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="input-group">
                                        <select class="form-control auto-submit" name="type">
                                            <option value="" {{$type == '' ? 'selected' : ''}}>{{ trans('message.chon_the_loai') }}</option>
                                            <option value="1" {{$type == 1 ? 'selected' : ''}}>{{ trans('message.tin_tuc') }}</option>
                                            <option value="2" {{$type == 2 ? 'selected' : ''}}>{{ trans('message.career') }}</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6 offset-3">
                                    <div class="input-group">
                                        <input placeholder="{{ trans('message.nhap_tieu_de_tin_tuc') }}" type="text" value="{{ Request::get('q', null) }}" name="q" class="form-control">
                                        <span class="input-group-append"> 
                                            <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-search"></i></button> 
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <br>
                        <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead>
                                    <tr>
                                        <th>{{trans('message.tieu_de')}}</th>
                                        <th class="text-center">{{ trans('message.hinh_anh') }}</th>
                                        <th>{{trans('message.mo_ta')}}</th>
                                        <th>{{ trans('message.hinh_anh') }}</th>
                                        <th>{{ trans('message.ngon_ngu') }}</th>
                                        <th>{{ trans('message.the_loai') }}</th>
                                        <th>{{ trans('message.trang_thai') }}</th>
                                        <th width="100px" class="text-center">{{ trans('message.thao_tac') }}</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                @if(isset($news) && $news->count() > 0)
                                    @foreach($news as $post)
                                    <?php $userCreate = \App\Models\User::find($post->created_by);?>
                                        <tr>
                                            <td>{{$post->title}}</td>
                                            <td class="feed-element text-center">
                                                <img alt="image" style="max-height: 50px " src="{{ Tool::getImage($post->avatar, \App\Helpers\Facades\Tool::getConst('POST_UPLOAD')) }}">
                                            </td>
                                            <td>{{$post->description}}</td>
                                            <td><?php echo $userCreate ? $userCreate->full_name : '';?></td>
                                            <td>{{$post->lang == 'vi' ? trans('message.tieng_viet') : trans('message.tieng_anh') }}</td>
                                            <td>{{$post->type == 1 ? trans('message.tin_tuc') : trans('message.career') }}</td>
                                            <td>{{$post->status == 1 ? trans('message.hoat_dong') : trans('message.tam_dung')}}</td>
                                            <td class="text-center no-wrap">
                                                <?php if ($post->status) {?>
                                                <form method="post" action="{{ route('news.delete', $post->id ) }}" accept-charset="UTF-8">
                                                    <input name="status" type="hidden" value="0">
                                                    <input name="_method" type="hidden" value="delete">
                                                    <?php if ($post->type == 1) {?>
                                                    <a title="Chi tiết" href="{{route('frontend.news.detail', ['slug' => $post->slug])}}" target="_blank" class="btn btn-white btn-sm"><i class="fa fa-eye"></i></a>
                                                    <?php } else {?>
                                                    <a title="Chi tiết" href="{{route('frontend.news.detailCareer', ['slug' => $post->slug])}}" target="_blank" class="btn btn-white btn-sm"><i class="fa fa-eye"></i></a>
                                                    <?php } ?>
                                                    {{ csrf_field() }}

                                                    @if (Entrust::can('news-edit'))
                                                        <a title="Sửa"
                                                           href="{{ route('news.edit',['id'=>$post->id]) }}"
                                                           class="btn btn-success btn-sm"><i class="fa fa-edit"></i></a>
                                                    @endif
                                                    @if (Entrust::can('news-delete'))
                                                        <button type="button" title="{{trans('message.xoa')}}"
                                                                onclick="event.preventDefault(); commonFunc.confirm(this, 'tin tức', 1, 'vi', 'false', '{{$post->name}}');"
                                                                class="btn btn-danger btn-sm"><i
                                                                    class="fa fa-trash-o"></i>
                                                        </button>
                                                    @endif
                                                </form>
                                                <?php } else {?>
                                                    <form method="post" action="{{ route('news.delete', $post->id ) }}" accept-charset="UTF-8">
                                                    <input name="status" type="hidden" value="1">
                                                    <input name="_method" type="hidden" value="delete">
                                                    {{ csrf_field() }}

                                                    @if (Entrust::can('news-edit'))
                                                        <a title="Sửa"
                                                           href="{{ route('news.edit',['id'=>$post->id]) }}"
                                                           class="btn btn-success btn-sm"><i class="fa fa-edit"></i></a>
                                                    @endif
                                                    @if (Entrust::can('news-create'))
                                                        <button type="submit" title="Add" class="btn btn-info btn-sm"><i class="fa fa-plus-square"></i> </button>
                                                    @endif
                                                </form>
                                                <?php } ?>
                                            </td>
                                        </tr>
                                    @endforeach
                                @endif
                                    </tbody>
                                </table>
                        </div>
                        
                        @if(isset($news) && $news->count() > 0)
                        <div class="row">
                            @includeif('partials.pagination', [
                                'pagination'  => $pagination,
                                'data'   => $news->toArray(),
                            ])
                        </div>
                        @else
                            @includeIf('partials.empty')
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@section('body_script')
    @includeif('partials.message')
@endsection